# Generated by Django 3.2.25 on 2024-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20240330_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(),
        ),
    ]
